# Generated by Django 3.2.4 on 2021-06-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210628_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
