# Generated by Django 3.2.4 on 2021-06-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210628_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
